### PR TITLE
Add agent based and assisted install support.

### PR DESCRIPTION
**Pull request by cs-zhang**

### CODE REVIEW

**Comment by dharaneeshvrd** [comment]
I have two comments.
1. Please see whether it would make sense to create a separate dir to place assisted and agent based SNO deployments Or if you think they need to be in a single dir, then we can move from `ocp-ci-hacks/sno/sno` to `ocp-ci-hacks/sno` itself instead of keeping a dup sno dir.
2. I am seeing public urls were to accessed [here](https://github.com/ppc64le-cloud/ocp-ci-hacks/pull/5/files#diff-c83cba5b72bd6aaf7c970d8161727a2b160b7c1b4e7252b46abda565d9ad607cR5) and [here](https://github.com/ppc64le-cloud/ocp-ci-hacks/pull/5/files#diff-c83cba5b72bd6aaf7c970d8161727a2b160b7c1b4e7252b46abda565d9ad607cR33) to create clusters and retrieve api token and all. If it can be reached from build cluster, then it's better to add them in actual workflow in openshift/release, we can keep this repo to keep scripts which need to be executed only inside bastion like reaching nodes within private network.

**Comment by cs-zhang** [comment]
1.  Yes, we can remove one layer of sno.
2.  The assisted installer need to access to redhat account to install a cluster, it is better to keep in same place as agent based installer and normal SNO. The script in workflow just for create the cluster env.

**Comment by dharaneeshvrd** [comment]
Ok let me know once you have removed one level sno of dir. We can merge it.

**Comment by cs-zhang** [comment]
Done.

**Pull request merged**
